name: Release to Develop Environment
on:
  push:
    branches:
      - develop
      
jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDDISqcbzNE/yGInEjRgssurBM+G7REFjkBUa8NU5ZZxQAAAJie+obmnvqG
5gAAAAtzc2gtZWQyNTUxOQAAACDDISqcbzNE/yGInEjRgssurBM+G7REFjkBUa8NU5ZZxQ
AAAECGxvMuA+Jc/02UcYiAuI3NdXdglY+uyfbyjdOwozIVc8MhKpxvM0T/IYicSNGCyy6s
Ez4btEQWOQFRrw1TllnFAAAADmdpdGh1Yi1hY3Rpb25zAQIDBAUGBw==
-----END OPENSSH PRIVATE KEY-----

          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            cd /home/xs475299/atsushi-web.site/public_html/test_ssh
            git checkout develop
            git pull origin develop