name: Release to Develop Environment
on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: sv14309.xserver.jp
          username: xs475299
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ""
          port: 10022
          debug: true
